name: Static analysis

on: pull_request

jobs:
  clang-tidy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@master
      with:
        language: c++
        use_cmake: true
